# This is a workflow to perform basic verification for KoLmafia ASH scripts

name: CI
env:
  MAFIA_BUILD: "1655"
  MAFIA_VERSION: "20147"
  SCRIPT_NAME: "excavator.ash"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8

    - name: Prepare KoLmafia
      run: |
        curl "https://ci.kolmafia.us/job/Kolmafia/${MAFIA_BUILD}/artifact/dist/KoLmafia-${MAFIA_VERSION}.jar" --output kolmafia.jar
        mkdir -p ~/.kolmafia/scripts/
    
    - name: Copy script to kolmafia folder
      run: cp -r ./RELEASE/scripts/* ~/.kolmafia/scripts/

    - name: Create test script
      run: echo "try { cli_execute('verify ${SCRIPT_NAME}'); } finally { cli_execute('exit'); }" > ~/.kolmafia/scripts/_ci.ash
    
    - name: Verify file
      run: |
        output=$(java -jar ./kolmafia.jar --CLI _ci)
        if [[ $output == *"Script verification complete." ]]; then
          exit 0;
        else
          echo $output;
          exit 1;
        fi
