# This workflow will do a clean install of node dependencies, build the source
# code across multiple Node.js versions, and lint the project.
name: Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check code formatting
        run: yarn run lint
