# This is a workflow to run our ETL script

name: ETL
env:
  KOL_USERNAME: "Excavator"
  KOL_PASSWORD: ${{ secrets.KOL_PASSWORD }}
  SPREADSHEET_ID: "1IZV-Rj6_mcuYcYQ-gBa_ZyghO9MXNQARL5MlSBwopMs"

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  etl:
    name: ETL
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Decrypt credentials
        run: gpg --quiet --batch --yes --decrypt --passphrase="$CREDENTIALS_PASSPHRASE" --output $GITHUB_WORKSPACE/packages/excavator-web/credentials.json $GITHUB_WORKSPACE/.github/secrets/credentials.json.gpg
        env:
          CREDENTIALS_PASSPHRASE: ${{ secrets.CREDENTIALS_PASSPHRASE }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.6.9'
          cache: 'pip'

      - name: Run ETL
        run: |
          python -m pip install -r ./packages/excavator-web/requirements.txt
          python ./packages/excavator-web/kmail-to-gsheet.py
